_schema: _schema
paths:
  uploads: static/uploads
  static: static
collections_config:
  config_default:
    path: config/_default
    name: Config Default
    icon: chair_alt
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  content_posts:
    path: exampleSite/content/blog
    name: Content Posts
    icon: content_paste
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  example_site:
    path: exampleSite
    name: Example Site
    icon: explicit
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  themes_geeky_hugo_data:
    path: themes/geeky-hugo/data
    name: Themes Geeky Hugo Data
    icon: emergency_heat
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
  custom_shortcodes:
    path: themes/geeky-hugo/layouts/shortcodes
    name: Custom Shortcodes
    icon: code
    description: 'Shortcodes personalizzati per il sito'
    _snippets:
      hugo_indice:
        snippet: "{{< indice >}}"
        inline: false
        preview:
          text: indice
        definitions:
          shortcode_name: indice
          content_key: inner_text
      
      hugo_image:
        snippet: "{{< image src=\"[[src]]\" alt=\"[[alt]]\" title=\"[[title]]\" >}}"
        inline: false
        preview:
          text: image
        definitions:
          src:
            type: text
            label: "Source URL"
          alt:
            type: text
            label: "Alt text"
          title:
            type: text
            label: "Image title"
      
      hugo_carousel:
        snippet: "{{< carousel images=\"[[images]]\" >}}"
        inline: false
        preview:
          text: carousel
        definitions:
          images:
            type: text
            label: "Images (comma separated)"
      
      hugo_leggi_anche:
        snippet: "{{< leggi-anche >}}"
        inline: false
        preview:
          text: leggi-anche
      
      hugo_extlink:
        snippet: "{{< extLink \"[[text]]\" \"[[url]]\" >}}"
        inline: false
        preview:
          text: extLink
        definitions:
          text:
            type: text
            label: "Link text"
          url:
            type: text
            label: "URL"
      
      hugo_citazione:
        snippet: "{{< citazione \"[[text]]\" >}}"
        inline: false
        preview:
          text: citazione
        definitions:
          text:
            type: text
            label: "Quote text"
      
      hugo_bold:
        snippet: "{{< bold \"[[text]]\" >}}"
        inline: false
        preview:
          text: bold
        definitions:
          text:
            type: text
            label: "Text to bold"
      
      hugo_underline:
        snippet: "{{< underline \"[[text]]\" >}}"
        inline: false
        preview:
          text: underline
        definitions:
          text:
            type: text
            label: "Text to underline"
      
      hugo_center:
        snippet: "{{< center >}}[[content]]{{< /center >}}"
        inline: false
        preview:
          text: center
        definitions:
          content:
            type: rich_text
            label: "Content to center"
      
      hugo_button:
        snippet: "{{< button >}}[[text]]{{< /button >}}"
        inline: false
        preview:
          text: button
        definitions:
          text:
            type: text
            label: "Button text"
      
      hugo_assicurazione:
        snippet: "{{< assicurazione >}}"
        inline: false
        preview:
          text: assicurazione
      
      hugo_animali:
        snippet: "{{< animali >}}"
        inline: false
        preview:
          text: animali
      
      hugo_sponsor:
        snippet: "{{< sponsor >}}"
        inline: false
        preview:
          text: sponsor
      
      hugo_paypal:
        snippet: "{{< paypal >}}"
        inline: false
        preview:
          text: paypal
      
      hugo_revolut:
        snippet: "{{< revolut >}}"
        inline: false
        preview:
          text: revolut
      
      hugo_youtube2:
        snippet: "{{< youtube2 id=\"[[video_id]]\" >}}"
        inline: false
        preview:
          text: youtube2
        definitions:
          video_id:
            type: text
            label: "YouTube video ID"
      
      hugo_gmap:
        snippet: "{{< gmap lat=\"[[latitude]]\" lng=\"[[longitude]]\" zoom=\"[[zoom]]\" >}}"
        inline: false
        preview:
          text: gmap
        definitions:
          latitude:
            type: number
            label: "Latitude"
          longitude:
            type: number
            label: "Longitude"
          zoom:
            type: number
            label: "Zoom level"
            default: 15
      
      hugo_omap:
        snippet: "{{< omap lat=\"[[latitude]]\" lng=\"[[longitude]]\" zoom=\"[[zoom]]\" >}}"
        inline: false
        preview:
          text: omap
        definitions:
          latitude:
            type: number
            label: "Latitude"
          longitude:
            type: number
            label: "Longitude"
          zoom:
            type: number
            label: "Zoom level"
            default: 15
      
      hugo_chart:
        snippet: "{{< chart >}}"
        inline: false
        preview:
          text: chart
      
      hugo_codepen:
        snippet: "{{< codepen >}}"
        inline: false
        preview:
          text: codepen
      
      hugo_procontro:
        snippet: "{{< procontro >}}"
        inline: false
        preview:
          text: procontro
      
      hugo_summary:
        snippet: "{{< summary >}}"
        inline: false
        preview:
          text: summary
      
      hugo_blogfooter:
        snippet: "{{< blogFooter >}}"
        inline: false
        preview:
          text: blogFooter
      
      hugo_sociallink:
        snippet: "{{< socialLink >}}"
        inline: false
        preview:
          text: socialLink
      
      hugo_social_follow:
        snippet: "{{< social-follow >}}"
        inline: false
        preview:
          text: social-follow
      
      hugo_card:
        snippet: "{{< card >}}"
        inline: false
        preview:
          text: card
      
      hugo_translateDate:
        snippet: "{{< translateDate >}}"
        inline: false
        preview:
          text: translateDate

timezone: Asia/Tokyo
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
