theme = "geeky-hugo"

# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown.
#
# The actual configuration files are stored in the `config/_default/` folder.

######################### site variables ##############################
# customize your color and font from here.
[params]
description = "Alla scoperta del mondo on the road. Unisciti al viaggio e lasciati ispirare a intraprendere la tua prossima avventura!"
title = "Vandipety | Esplora il Mondo in Camper insieme a noi"
ai_summary_enabled = true

# Ottimizzazioni per le performance
[params.performance]
enable_critical_css = true
enable_lazy_loading = true
enable_resource_hints = true
enable_service_worker = false
minify_html = true
minify_css = true
minify_js = true

[params.variables]
color_primary = "#15817f"
body_color = "#FFF"
text_color = "#555"
text_dark = "#222"
text_light = "#999"
border_color = "#E1E1E1"
black = "#000"
white = "#FFF"
light = "#f2f2f2"

# font variables
# base font size for full website, 
font_size = "15px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.3" # default is "majorThird": 1.25

# Give your font name from google font. add font weight using ":wght@" and separate by ";"
# example: "Work Sans:wght@400"
font_primary = "Raleway:wght@400"
font_primary_type = "sans-serif" # [serif/sans-serif]
font_secondary = "Merriweather Sans:wght@400;700"
font_secondary_type = "sans-serif" # [serif/sans-serif]
font_icon = "Font Awesome 5 Free"


############################# Plugins ##############################

# CSS Plugins - Commentati per caricamento asincrono
# [[params.plugins.css]]
# link = "assets/plugins/font-awesome/fontawesome.min.css"
# [[params.plugins.css]]
# link = "assets/plugins/font-awesome/brands.css"
# [[params.plugins.css]]
# link = "assets/plugins/font-awesome/solid.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "https://cdn.jsdelivr.net/npm/fuse.js@7.1.0"
[[params.plugins.js]]
link = "https://cdn.jsdelivr.net/npm/mark.js@8.11.1/dist/mark.min.js"
[[params.plugins.js]]
link = "assets/plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/webfont-loader/webfont-loader-2.min.js"
[[params.plugins.js]]
link = "plugins/money.min.js"

[outputs]
    home = ["HTML", "RSS", "JSON"]

# Ottimizzazioni per la build
[build]
writeStats = true

# Configurazioni per le performance
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# Ottimizzazioni per le immagini
[imaging]
quality = 85
resampleFilter = "Lanczos"
anchor = "Smart"

# Configurazioni per i media
[mediaTypes]
[mediaTypes."text/css"]
suffixes = ["css"]
[mediaTypes."application/javascript"]
suffixes = ["js"]

# Output formats ottimizzati
[outputFormats]
[outputFormats.CSS]
mediaType = "text/css"
isPlainText = true
notAlternative = true
[outputFormats.JS]
mediaType = "application/javascript"
isPlainText = true
notAlternative = true
