[build]
  publish = "exampleSite/public"
  command = "tinacms build && cd exampleSite && hugo --minify --gc --themesDir ../themes --theme geeky-hugo"
  
[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

[[headers]]
  for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"
  Referrer-Policy = "same-origin"
  Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, OPTIONS"
  Access-Control-Allow-Headers = "Content-Type, Authorization"