[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --minify --gc --themesDir ../themes --theme geeky-hugo"
  
[build.environment]
  HUGO_VERSION = "0.145.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "SAMEORIGIN"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Compressione
[[headers]]
  for = "/*"
  [headers.values]
    Content-Encoding = "gzip"