[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

# Cache headers per risorse statiche
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/plugins/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers per sicurezza
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Redirect per font (se necessario)
[[redirects]]
  from = "/fonts/*"
  to = "/fonts/:splat"
  status = 200
  headers = {Access-Control-Allow-Origin = "*"}