############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

# [[main]]
# name = "Attrezzature"
# url = "gears/"
# weight = 2

[[main]]
name = "Il viaggio"
url = "trip/"
weight = 2

[[main]]
name = "Le spese"
url = "expanses/"
weight = 2

[[main]]
name = "Il van"
url = "van/"
weight = 3

# [[main]]
# name = "Diamo i numeri"
# url = "#"
# weight = 3
# hasChildren = true

#   [[main]]
#   parent = "Diamo i numeri"
#   name = "Il viaggio"
#   url = "trip/"
#   weight = 1

#   [[main]]
#   parent = "Diamo i numeri"
#   name = "Le spese"
#   url = "expanses/"
#   weight = 2

#   [[main]]
#   parent = "Diamo i numeri"
#   name = "Il van"
#   url = "van/"
#   weight = 3

[[main]]
name = "Libri"
url = "books/"
weight = 4

# [[main]]
# name = "Il Record"
# url = "record/"
# weight = 5

[[main]]
name = "Chi siamo"
url = "#"
weight = 6
hasChildren = true

  [[main]]
  parent = "Chi siamo"
  name = "Vandipety"
  url = "about/"
  weight = 1

  [[main]]
  parent = "Chi siamo"
  name = "Parlano di noi"
  url = "press/"
  weight = 2

  [[main]]
  parent = "Chi siamo"
  name = "Contatti"
  url = "contact/"
  weight = 3
  
# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Chi siamo"
url = "about/"
weight = 2

[[footer]]
name = "Contatti"
url = "contact/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
