############# English navigation ##############

# main menu
[[main]]
name = "Articoli"
url = ""
weight = 1

[[main]]
name = "Chi Siamo"
url = "about/"
weight = 2

[[main]]
name = "Libri"
url = "books/"
weight = 3

# [[main]]
# name = "Attrezzature"
# url = "gears/"
# weight = 4

# [[main]]
# name = "Spese"
# url = "expense/"
# weight = 5

[[main]]
name = "Pagine"
url = "#"
weight = 6
hasChildren = true

  [[main]]
  parent = "Pagine"
  name = "Tags"
  url = "tags/"
  weight = 1

  [[main]]
  parent = "Pagine"
  name = "Categorie"
  url = "categories/"
  weight = 2

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Chi Siamo"
url = "about/"
weight = 2

# [[footer]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 4
