############# English navigation ##############

# main menu
[[main]]
name = "Blog"
url = ""
weight = 1

# [[main]]
# name = "Attrezzature"
# url = "gears/"
# weight = 2

[[main]]
name = "Diamo i numeri"
url = "#"
weight = 3
hasChildren = true

  [[main]]
  parent = "Diamo i numeri"
  name = "Il viaggio"
  url = "trip/"
  weight = 1

  [[main]]
  parent = "Diamo i numeri"
  name = "Le spese"
  url = "expanses/"
  weight = 2

  [[main]]
  parent = "Diamo i numeri"
  name = "Il van"
  url = "van/"
  weight = 3


[[main]]
name = "Libri"
url = "books/"
weight = 4

[[main]]
name = "Chi Siamo"
url = "about/"
weight = 6

[[main]]
name = "Parlano di noi"
url = "press/"
weight = 7

# [[main]]
# name = "Pagine"
# url = "#"
# weight = 6
# hasChildren = true

#   [[main]]
#   parent = "Pagine"
#   name = "Tags"
#   url = "tags/"
#   weight = 1

#   [[main]]
#   parent = "Pagine"
#   name = "Categorie"
#   url = "categories/"
#   weight = 2

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Contatti"
url = "contact/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
