about_widget_content = "Se sentite ridere in lontananza potremmo essere noi."
address = ""
author = "Themefisher"
contact_form_action = "#"
copyright = ""
custom_script = ""
description = "This is meta description"
email = "info@email.com"
favicon = "images/favicon.png"
featured_post_title = "In primo piano"
footer_content = "Se sentite ridere in lontananza potremmo essere noi."
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "Boilerplate"
logo_width = "150x"
mainSections = ["blog"]
mobile = ""
navbar_fixed = false
recent_post_title = "Post recenti"
search = true
[advertisement]
image = ""
link = "https://gethugothemes.com/"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Conoscici meglio"
button_link = "about/"
content = "Siamo Paolo, Sara, Olimpia e Sakè e giriamo per il mondo raccontando qui le nostre avvenure."
enable = true
image = "images/banner.png"
title_large = "Benvenuti **!**"
title_small = "nel Blog del Gatto di Cit Turin"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = false
expire_days = 2
[preloader]
enable = false
preloader = ""
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/ilgattodicitturin/"
title = "instagram"
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/ilgattodicitturin"
title = "facebook"
[[social]]
icon = "fab fa-tiktok"
link = "https://vm.tiktok.com/ZMLJmLRTV/"
title = "TikTok"
[[social]]
icon = "fas fa-store"
link = "https://www.artpetfood.it/discount/SAK%25C3%2588OLIMPIA"
title = "Negozio"
