about_widget_content = "Se sentite ridere in lontananza potremmo essere noi."
address = ""
author = "Sara"
contact_form_action = "javascript: sendMail();"
copyright = ""
custom_script = ""
description = ""
email = "info@vandipety.it"
emailSponsor = "sponsor@vandipety.it"
favicon = "images/favicon.png"
featured_post_title = "In primo piano"
footer_content = "Se sentite ridere in lontananza potremmo essere noi."
image = "images/logo.png"
logo = "images/logo.png"
logoPlain = "images/logoPlain.png"
logoTxt = "images/logo_text.png"
logo2 = "images/logo2.png"
logo_text = "Boilerplate"
logo_width = "150px"
logo_height = "150px"
mainSections = ["blog"]
mobile = ""
navbar_fixed = false
recent_post_title = "Post recenti"
search = true
[advertisement]
image = ""
link = "https://gethugothemes.com/"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Conoscici meglio"
button_link = "about/"
content = "Siamo Paolo, Sara, Olimpia e Sakè e giriamo per il mondo raccontando qui le nostre avventure."
enable = true
image = "images/banner.png"
title_large = "Benvenuti **!**"
title_small = "nel Blog di Vandipety"
[cookies]
button = "Accetto"
content = "Questo sito utilizza i cookie. Continuando a utilizzare questo sito Web, acconsenti al loro utilizzo."
enable = true
expire_days = 7
[preloader]
enable = false
preloader = ""
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[widgets]
sidebar = ["newsletter", "tappe", "categories", "recent-post"]
[[social]]
icon = "fab fa-youtube"
link = "https://www.youtube.com/channel/UCH3tGEnOnx6ql48zZTSiFvw"
title = "youtube"
[[social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/vandipety/"
title = "instagram"
# [[social]]
# icon = "fab fa-tiktok"
# link = "https://vm.tiktok.com/ZMLJmLRTV/"
# title = "TikTok"
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/ilgattodicitturin"
title = "facebook"
#[[social]]
# icon = "fas fa-store"
# link = "https://www.almonature.com"
# title = "Negozio"
