backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Editorial workflow - posts go through draft/review/ready process
publish_mode: editorial_workflow

# Media storage configuration for Hugo
media_folder: "static/images/uploads" # Media files stored in repo
public_folder: "/images/uploads" # Public URL path for uploaded media

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image", required: false, hint: "Upload image or use Cloudinary URL" }
      - { label: "Publish Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss", format: "YYYY-MM-DDTHH:mm:ss.sssZ" }
      - { label: "Categories", name: "categories", widget: "list", allow_add: true, default: ["Blog"] }
      - { label: "Type", name: "type", widget: "select", options: ["featured", "regular"], default: "regular", required: false }
      - { label: "Continent", name: "continent", widget: "string", required: false, hint: "e.g., Europa, Asia, Africa" }
      - { label: "Country", name: "country", widget: "string", required: false, hint: "Country name in Italian" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Static Pages"
    files:
      - label: "Chi Siamo (About)"
        name: "about"
        file: "content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "Layout", name: "layout", widget: "hidden", default: "about" }
          - { label: "Body", name: "body", widget: "markdown" }
      
      - label: "Contact"
        name: "contact"
        file: "content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
      
      - label: "Van"
        name: "van"
        file: "content/van.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
      
      - label: "Trip"
        name: "trip"
        file: "content/trip.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
      
      - label: "Books"
        name: "books"
        file: "content/books.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
      
      - label: "Privacy Policy"
        name: "privacy"
        file: "content/privacy-policy.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Body", name: "body", widget: "markdown" }
